- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Set archtype in amd64 architecture
  ansible.builtin.set_fact:
    arch_type: amd64
  when: ansible_architecture == 'x86_64' or ansible_architecture == 'amd64'

- name: Set archtype in aarch64 architecture
  ansible.builtin.set_fact:
    arch_type: arm64
  when: ansible_architecture == 'arm64' or ansible_architecture == 'aarch64'

- name: Download kubectl
  ansible.builtin.get_url:
    url: https://s3.us-west-2.amazonaws.com/amazon-eks/1.28.3/2023-11-14/bin/linux/{{ arch_type }}/kubectl
    dest: /usr/bin/kubectl
    mode: '0755'

- name: Install kubernetes python package
  ansible.builtin.pip:
    name: kubernetes
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: 1

- name: Install kubernetes.core ansible galaxy collection
  community.general.ansible_galaxy_install:
    type: collection
    name: kubernetes.core
