- hosts: localhost
  connection: local
  become: true
  roles:
    - base

  tasks:
    - include_role:
        name: configure_k8s
      vars:
        k8s_provider: minikube 
        minikube_local_api_server_ip: 192.168.100.143
        minikube_local_api_server_port: 65408
        #k8s_provider: eks
        #aws_region: eu-west-1
        #aws_cluster_name: av-staging

    - block:
        - name: Creating av-app application state
          ansible.builtin.command: kubectl create cm av-app-state --from-literal=version=0
      rescue:
        - fail:
            msg: >
              Oops! the application already exist

    - name: Deploying the av-app with v0 version
      include_role:
        name: kubernetes_app
      vars:
        version: v0
        pvc_storage_class: standard
        namespace: default
        env: staging
        action: present

    - block:
        - name: Getting av-app blue version from state
          ansible.builtin.command: kubectl get cm av-app-state -o jsonpath='{.data.version}'
          register: blue_version_command
      rescue:
        - fail:
            msg: >
              Error! the application state has some problem

    - set_fact:
        blue_version_number: "{{ blue_version_command.stdout }}"

    - name: Deploying the av-app lb with v0 version
      include_role:
        name: kubernetes_lb
      vars:
        acm_arn: arn:aws:acm:us-east-1:377533143757:certificate/eb6da30a-73cd-4a0b-ac0f-089bf3cd3798
        version: v{{ blue_version_number }}
        namespace: default
        env: staging
