- name: Applying av-app LB service
  kubernetes.core.k8s:
    state: "present"
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: av-app-lb-svc
        namespace: "{{ namespace }}"
        labels:
          app: av-app
          component: web
          version: "{{ version }}"
          env: "{{ env }}"
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "{{ acm_arn }}"
      spec:
        type: LoadBalancer
        selector:
          app: av-app
          component: web
          version: "{{ version }}"
          env: "{{ env }}"
        ports:
          - name: http
            protocol: TCP
            port: 80
            targetPort: 5002
          - name: https
            protocol: TCP
            port: 443
            targetPort: 5002